[o2switch]
type = sftp
host = CHANGER_HOST_O2SWITCH
user = CHANGER_UTILISATEUR_O2SWITCH
port = 22
# Option 1: mot de passe chiffre par rclone (commande: rclone obscure "votre_mot_de_passe")
pass = CHANGER_MOT_DE_PASSE_OBSCUR
# Option 2: commenter pass et utiliser une cle SSH
# key_file = C:/Users/VOTRE_USER/.ssh/id_ed25519
# use_insecure_cipher = false
