[o2switch]
type = ftp
host = ftp.kujo2727.odns.fr
user = kujo2727@clinikauto.fr
port = 21
tls = false
explicit_tls = true
no_check_certificate = true
pass = tGvqQvnnf3ueMywm9WBnsSmYwaVeavE4bOneM-f597Y
